<div class="block">
    <div class="block-title"><strong><?php echo __('Information') ?></strong></div>
    <div class="block-content">
        <ul class="links">
            <li><a href="<?php echo $this->getUrl('about-us') ?>" title="<?php echo __('About Us') ?>"><?php echo __('About Us') ?></a></li>
            <li><a href="<?php echo $this->getUrl('swiss-dealers') ?>" title="<?php echo __('Swiss Dealers') ?>"><?php echo __('Swiss Dealers') ?></a></li>
            <li><a href="<?php echo $this->getUrl('international-dealers') ?>" title="<?php echo __('International Dealers') ?>"><?php echo __('International Dealers') ?></a></li>
            <li><a href="<?php echo $this->getUrl('prices') ?>" title="<?php echo __('Prices') ?>"><?php echo __('Prices') ?></a></li>
            <li><a href="<?php echo $this->getUrl('shipping') ?>" title="<?php echo __('Shipping Costs') ?>"><?php echo __('Shipping Costs') ?></a></li>
            <li><a href="<?php echo $this->getUrl('privacy') ?>" title="<?php echo __('Privacy and Data Protection') ?>"><?php echo __('Privacy and Data Protection') ?></a></li>
            <li><a href="<?php echo $this->getUrl('terms-and-conditions') ?>" title="<?php echo __('Terms and Conditions') ?>"><?php echo __('Terms and Conditions') ?></a></li>
            <li><a href="<?php echo $this->getUrl('returns') ?>" title="<?php echo __('Right of Returns') ?>"><?php echo __('Right of Returns') ?></a></li>
        </ul>
    </div>
</div>
<div class="block">
    <div class="block-title"><strong><?php echo __('Links') ?></strong></div>
    <div class="block-content">
        <ul class="links">
            <li><a href="<?php echo $this->getUrl('contact') ?>" title="<?php echo __('Contact Us') ?>"><?php echo __('Contact Us') ?></a></li>
            <li><a href="<?php echo $this->getUrl('customer/account') ?>" title="<?php echo __('My Account') ?>"><?php echo __('My Account') ?></a></li>
            <li><a href="<?php echo $this->getUrl('sales/order/history') ?>" title="<?php echo __('Orders') ?>"><?php echo __('Orders') ?></a></li>
            <li><a href="<?php echo $this->getUrl('catalogsearch/advanced') ?>" title="<?php echo __('Advanced Search') ?>"><?php echo __('Advanced Search') ?></a></li>
            <li><a href="<?php echo $this->getUrl('webcams') ?>" title="<?php echo __('Webcams') ?>"><?php echo __('Webcams') ?></a></li>
        </ul>
    </div>
</div>
<?php echo $this->getChildHtml('footer_contact_information') ?>
