<?php
    $footer = $this->getConfig('porto_settings/footer');
?>
<div class="footer">
    <div class="footer-middle">
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <?php echo $this->getChildHtml('footer_contact_information') ?>
                </div>
                <div class="col-sm-8">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="block">
                                <div class="block-title"><strong><?php echo __('Links') ?></strong></div>
                                <div class="block-content">
                                    <ul class="links">
                                        <li><em class="porto-icon-right-dir theme-color"></em><a href="<?php echo $this->getUrl('contact') ?>" title="<?php echo __('Contact Us') ?>"><?php echo __('Contact Us') ?></a></li>
                                        <li><em class="porto-icon-right-dir theme-color"></em><a href="<?php echo $this->getUrl('customer/account') ?>" title="<?php echo __('My Account') ?>"><?php echo __('My Account') ?></a></li>
                                        <li><em class="porto-icon-right-dir theme-color"></em><a href="<?php echo $this->getUrl('sales/order/history') ?>" title="<?php echo __('Orders') ?>"><?php echo __('Orders') ?></a></li>
                                        <li><em class="porto-icon-right-dir theme-color"></em><a href="<?php echo $this->getUrl('catalogsearch/advanced') ?>" title="<?php echo __('Advanced Search') ?>"><?php echo __('Advanced Search') ?></a></li>
                                        <li><em class="porto-icon-right-dir theme-color"></em><a href="<?php echo $this->getUrl('webcams') ?>" title="<?php echo __('Webcams') ?>"><?php echo __('Webcams') ?></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="block">
                                <div class="block-title"><strong><?php echo __('Information') ?></strong></div>
                                <div class="block-content">
                                    <ul class="links">
                                        <li><em class="porto-icon-right-dir theme-color"></em><a href="<?php echo $this->getUrl('about-us') ?>" title="<?php echo __('About Us') ?>"><?php echo __('About Us') ?></a></li>
                                        <li><em class="porto-icon-right-dir theme-color"></em><a href="<?php echo $this->getUrl('about-x-dream-fly') ?>" title="<?php echo __('About X-Dream Fly') ?>"><?php echo __('About X-Dream Fly') ?></a></li>
                                        <li><em class="porto-icon-right-dir theme-color"></em><a href="<?php echo $this->getUrl('swiss-dealers') ?>" title="<?php echo __('Swiss Dealers') ?>"><?php echo __('Swiss Dealers') ?></a></li>
                                        <li><em class="porto-icon-right-dir theme-color"></em><a href="<?php echo $this->getUrl('international-dealers') ?>" title="<?php echo __('International Dealers') ?>"><?php echo __('International Dealers') ?></a></li>
                                        <li><em class="porto-icon-right-dir theme-color"></em><a href="<?php echo $this->getUrl('prices') ?>" title="<?php echo __('Prices') ?>"><?php echo __('Prices') ?></a></li>
                                        <li><em class="porto-icon-right-dir theme-color"></em><a href="<?php echo $this->getUrl('shipping') ?>" title="<?php echo __('Shipping Costs') ?>"><?php echo __('Shipping Costs') ?></a></li>
                                        <li><em class="porto-icon-right-dir theme-color"></em><a href="<?php echo $this->getUrl('download') ?>" title="<?php echo __('Downloads') ?>"><?php echo __('Downloads') ?></a></li>
                                        <li><em class="porto-icon-right-dir theme-color"></em><a href="<?php echo $this->getUrl('privacy') ?>" title="<?php echo __('Privacy and Data Protection') ?>"><?php echo __('Privacy and Data Protection') ?></a></li>
                                        <li><em class="porto-icon-right-dir theme-color"></em><a href="<?php echo $this->getUrl('terms-and-conditions') ?>" title="<?php echo __('Terms and Conditions') ?>"><?php echo __('Terms and Conditions') ?></a></li>
                                        <li><em class="porto-icon-right-dir theme-color"></em><a href="<?php echo $this->getUrl('returns') ?>" title="<?php echo __('Right of Returns') ?>"><?php echo __('Right of Returns') ?></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="block-bottom">
<!--                                <div class="custom-block" style="float:left;"><img src="<?php echo $this->getMediaUrl('wysiwyg/smartwave/porto/footer/payment-icon.png') ?>"  style="max-width: 100%;" alt="" /></div>-->
                                <div class="social-icons" style="float:right;">
                                    <a href="https://www.facebook.com/flugsau" title="Facebook" target="_blank"><i class="porto-icon-facebook"></i></a>
                                    <a href="https://instagram.com/flugsaugmbh" title="Instagram" target="_blank"><i class="porto-icon-instagram"></i></a>
                                </div>
                                <address style="float:right; margin-right: 44px;margin-top:10px;font-size:11px;">© Flugsau GmbH. 2018. All Rights Reserved</address>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<a href="javascript:void(0)" id="totop"><em class="porto-icon-up-open"></em></a>
