<?php /** @var \Flugsau\Shop\Block\StoreInformation $block */ ?>
<div class="block">
    <div class="block-title"><strong><span><?php echo __('Contact') ?></span></strong></div>
    <div class="block-content">
        <ul class="contact-info links">
            <li>
                <p>
                    <b><?php echo __('Address') ?></b><br/>
                        <?php echo $block->getAddress() ?>
                </p>
            </li>
            <li>
                <p>
                    <b><?php echo __('Phone') ?></b><br/>
                    <?php echo $block->getPhoneNumber() ?>
                </p>
            </li>
            <li>
                <p>
                    <b><?php echo __('Email') ?></b><br/>
                    <a class="email" href="mailto:info@flugsau.ch">info@flugsau.ch</a>
                </p>
            </li>
            <li>
                <p>
                    <b><?php echo __('Opening hours') ?></b><br/>
                    <?php echo $block->getHours() ?>
                </p>
            </li>
        </ul>
    </div>
</div>
