<div class="home-teaser-wrapper">
    <div class="home-teaser">
        <div class="home-teaser-video">
            <iframe src="https://player.vimeo.com/video/166916811?loop=1&title=0&byline=0&portrait=0" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>
        <div class="home-teaser-text">
            <p><?php echo __('home-teaser-line-1') ?></p>
            <p><?php echo __('home-teaser-line-2') ?></p>
            <p><?php echo __('home-teaser-line-3') ?></p>
        </div>
    </div>
</div>
