<div class="home-teaser-wrapper">
    <div class="home-teaser">
        <div class="home-teaser-video">
            <iframe src="https://player.vimeo.com/video/166916811?loop=1&title=0&byline=0&portrait=0" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>
        <div class="home-teaser-text">
            <p>Die Schweizer Gurtzeug- und Zubehör Manufaktur im Engelbergertal.</p>
            <p>Entwicklung, Vertrieb und Produktion.</p>
            <p>Made in Grafenort.</p>
        </div>
    </div>
</div>
