<div class="home-teaser-wrapper">
    <div class="home-teaser">
        <div class="home-teaser-video">
            <iframe src="https://player.vimeo.com/video/166916811?loop=1&title=0&byline=0&portrait=0" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>
        <div class="home-teaser-text">
            <h1><?php echo __('home-teaser-title') ?></h1>
            <p><?php echo __('home-teaser') ?></p>
        </div>
    </div>
</div>
