
<div class="home-teaser-wrapper">
    <div class="home-teaser">
        <div class="home-teaser-text home-teaser-text-wide">
            <p><?php echo __('home-teaser2-p1') ?></p>
            <strong><?php echo __('Our services') ?></strong>
            <ul>
                <li><?php echo __('home-teaser2-list1') ?></li>
                <li><?php echo __('home-teaser2-list2') ?></li>
                <li><?php echo __('home-teaser2-list3') ?></li>
                <li><?php echo __('home-teaser2-list4') ?></li>
                <li><?php echo __('home-teaser2-list5') ?></li>
            </ul>
        </div>
    </div>
</div>
