<?php 
    /** @var \Magento\Catalog\Block\Product\View $block */
    $product = $block->getProduct();
?>
<div class="product-banner">
    <div class="product-banner-image">
        <img src="<?= $block->getImageUrl($product) ?>" alt="<?= $product->getName() ?>" />
    </div>
    <div>
        <div class="product-banner-name"><?= $product->getName() ?></div>
        <div class="product-banner-link"><a class="button" href="<?= $block->getProductUrl($product) ?>"><?= __('to the product') ?></a></div>
    </div>
</div>
