<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>

<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <div class="stock available" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
            <span><?= /* @escapeNotVerified */ __('In stock') ?></span>
        </div>
        <?php if ($_product->getCustomAttribute('delivery_time_from') && $_product->getCustomAttribute('delivery_time_to')): ?>
            <div>
                <?= __('Delivery time') ?>:&nbsp;<?= $_product->getCustomAttribute('delivery_time_from')->getValue() ?>&nbsp;-&nbsp;<?= $_product->getCustomAttribute('delivery_time_to')->getValue() ?>&nbsp;<?= __('days') ?>
            </div>
        <?php endif; ?>
    <?php else: ?>
        <div class="stock unavailable" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
            <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
