<!DOCTYPE html>
<html>
	<head>
		<title><?php echo $pageTitle; ?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
		<link rel='stylesheet' type='text/css' href='<?php echo $styleUrl; ?>' />
	</head>
<body>
	<div class="section nav">
		<div class="wrap">
			<div class="menu-item one-third column text-left">
				<a class="back-link" href="<?php echo $cancelUrl; ?>" target="_self">&nbsp;&nbsp;<?php echo $backToOrderText; ?></a>
			</div>
			<div class="menu-item one-third column text-center text-uppercase">
				<a href="http://www.twint.ch" target="_blank"><div class="twint-logo"></div> <div class="icon-info"></div></a>
			</div>
		</div>
	</div>
	<div class="section nav-mobile hidden">
		<div class="wrap">
			<div class="menu-item one-third column text-left">
				<a class="logo" href="http://www.twint.ch" target="_blank"><div class="twint-logo"></div></a>
			</div>
			<div class="menu-item one-third column text-center">
			</div>
		</div>
	</div>
	<div class="section header">
		<div class="wrap">
			<div class="header-item one-merge column text-center text-uppercase">
				<span class="value"><?php echo $amount; ?></span>
			</div>
		</div>
	</div>
	<div class="section header-mobile hidden">
		<div class="row text-center">
			<div class="text-uppercase">
				<a class="button back-button" href="#" target="_self"><?php echo $backText; ?></a>
				<a class="button info-button" href="http://www.twint.ch" target="_blank"><?php echo $informationText; ?></a>
			</div>
		</div>
		<div class="row text-center text-uppercase">
			<div>
				<p class="value"><?php echo $amount; ?></p>
			</div>
		</div>
	</div>
	<div class="section page">
		<div class="row text-center" id="app-chooser-container" style="display:none;">
			<div class="app-chooser-title">
				<?php echo $chooseText; ?>
			</div>
			<div class="app-logos-container">
				<a class="bank-logo bank-ubs" href="twint-issuer2://<?php echo $iOSLinkSuffix; ?>"></a>
				<a class="bank-logo bank-raiffeisen" href="twint-issuer6://<?php echo $iOSLinkSuffix; ?>"></a>
				<a class="bank-logo bank-pf" href="twint-issuer7://<?php echo $iOSLinkSuffix; ?>"></a>
				<a class="bank-logo bank-zkb" href="twint-issuer3://<?php echo $iOSLinkSuffix; ?>"></a>
				<a class="bank-logo bank-cs" href="twint-issuer4://<?php echo $iOSLinkSuffix; ?>"></a>
				<a class="bank-logo bank-bcv" href="twint-issuer5://<?php echo $iOSLinkSuffix; ?>"></a>
			</div>
			<div class="copy-cache">
				<select class="app-chooser" id="app-chooser">
					<option value=""><?php echo $otherBanksText; ?></option>
					<?php foreach ($issuers as $issuer): ?>
						<option value="<?php echo $issuer['issuerUrlScheme']; ?>"><?php echo $issuer['displayName']; ?></option>
					<?php endforeach;?>
				</select>
			</div>
		</div>
		<div class="row text-center">
			<div class="wrap">
				<div class="copy-cache">
					<button type="button" class="btn" id="pay-with-twint">
                        <?php echo $switchText; ?>
					</button>
				</div>
			</div>
		</div>
		<div class="row text-center">
			<div class="wrap or-wrapper">
				<h2><span class="or"><?php echo $orText; ?><span></h2>
			</div>
			<div class="alternative-text copy-cache"><?php echo $enterText; ?></div>
		</div>
		<div class="row white-bg text-center">
			<div class="wrap">
				<div class="credentials">
					<div class="credentials-box credential-token text-center text-uppercase float-rt">
						<div class="credentials-item">
							<?php foreach ($numericCode as $digit): ?>
								<p class="credential-number"><?php echo $digit; ?></p>
						    <?php endforeach; ?>
						</div>
					</div>
				</div>
			</div>
			<input type="text" value ="<?php echo $numericCodeRaw; ?>" id="tokenHolder" style="border: 0; outline: 0; color: white; font-size: 16px;">
		</div>
		<div class="row text-center" style="margin-top: 20px;">
			<div class="wrap">
				<div class="copy-cache">
					<button type="button" class="secondary btn" id="copy-token">
						<?php echo $copyText; ?>
					</button>
				</div>
			</div>
		</div>
	</div>
	
	
	<script src='<?php echo $appSwitchUrl; ?>' ></script>
	<script>twintRedirect.init("<?php echo $numericCodeRaw; ?>");</script>
	<?php echo $script; ?>
</body>
</html>